//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movimiento()
        {
            this.DetalleMovimiento = new HashSet<DetalleMovimiento>();
        }
    
        public int MovimientoId { get; set; }
        public int Tecla { get; set; }
        public string Nombre { get; set; }
        public int NroMovimientos { get; set; }
        public int PersonajeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMovimiento> DetalleMovimiento { get; set; }
        public virtual Personaje Personaje { get; set; }
    }
}
